version: 1.0.{build}
image: Visual Studio 2017
cache:
  - C:\maven\
  - C:\Users\appveyor\.m2\repository
build_script:
  - SET JAVA_HOME=C:\Program Files\Java\jdk10
  - SET PATH=C:\Program Files\Java\jdk10\bin;%PATH%
  - cmd: mvn -P MINPARALLEL,ALLMODULES,REDUCED_JPA_TESTS clean install
